<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends EntityRepository
{


    public function getMaxTicketByDate($dateVisite)
    {
        return $this
            ->createQueryBuilder('t')
            ->innerJoin('t.commande', 'cmd')
            ->select('COUNT(t)')
            ->where('cmd.dateVisite = :dateVisite')
            ->setParameter('dateVisite', $dateVisite)
            ->getQuery()
            ->getSingleScalarResult();
    }

}
