# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.calculprix:
      class: AppBundle\Services\CalculPrix\CalculPrix
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"

  app.max_ticket_by_day:
      class: AppBundle\Validator\Constraints\MaxTicketsByDay
      arguments:
          - "@doctrine.orm.entity_manager"
          - "@service_container"
      tag:
        - { name : validator.constraint_validator }
