# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.calculprix:
      class: AppBundle\Services\CalculPrix\CalculPrix
      arguments:
          - "@doctrine.orm.entity_manager"

  app.max_tickets_by_day_validator:
      class: AppBundle\Validator\Constraints\MaxTicketsByDayValidator
      arguments:
          - "@doctrine.orm.entity_manager"
      tags:
        - { name : validator.constraint_validator }

  app.codeResa:
      class: AppBundle\Services\CodeResa\CodeResa
      arguments:
          - "@doctrine.orm.entity_manager"
